---
# defaults file for ansible-role-winpackages
ansible_user: Administrator
ansible_password: "{{ admin_pass }}"
ansible_port: 5986
ansible_connection: winrm
# The following is necessary for Python 2.7.9+ (or any older Python that has backported SSLContext, eg, Python 2.7.5 on RHEL7) when using default WinRM self-signed certificates:
ansible_winrm_server_cert_validation: ignore
admin_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62663434326166316264303235623834633631383537643962393736653732373236663532353063
          6263333761356237363065383265626630303464303030620a626139326266393631306364633662
          33613161336164343434643261353164666534356466386334646532313232333264656435316532
          6432343261343535630a383736656461663033636339346362643461366461633062656463616534
          6536
